Lab02/WebApplication1/Models/CarViewModel.cs
namespace WebApplication1.Models
{
    public class CarViewModel
    {
        public int ID { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int TopSpeed { get; set; }

    }
}

Lab02/WebApplication1/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CarController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(CarViewModel viewModel)
        {
            this.ViewBag.Message = $"{viewModel.Brand} {viewModel.Model} added to favorites!";
            return View("Info", viewModel);
        }
        [HttpGet]
        [Route("/browse")]
        public IActionResult List()
        {
            List<CarViewModel> list = new List<CarViewModel>();
            list.Add(new CarViewModel() { Brand="Kia", Model="Ceed", TopSpeed=180 });
            list.Add(new CarViewModel() { Brand = "Fiat", Model = "500", TopSpeed = 190 });
            list.Add(new CarViewModel() { Brand = "BMW", Model = "X5", TopSpeed = 250 });
            return View(list);
        }
    }
}

Lab02/WebApplication1/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class RegistrationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Register(string email, bool consent, int age)
        {
            if (age < 18)
                this.ViewBag.Message = "You need to be older than 18 years to register here! ";
            else if (consent == false)
                this.ViewBag.Message = "Consent not provided!";
            else
                this.ViewBag.Message = $"User {email} registered!";
            return View("Index");
        }
    }
}

Lab02/WebApplication1/Views/Car/Index.cshtml
@model CarViewModel
<form asp-action="Index" asp-controller="Car">
    <h4>Car</h4>
    <hr />
    <input asp-for="@Model.ID" type="hidden"/>
    <br />
    <label asp-for="@Model.Brand"></label>
    <input asp-for="@Model.Brand" />
    <br />
    <label asp-for="@Model.Model"></label>
    <input asp-for="@Model.Model" />
    <br />
    <label asp-for="@Model.TopSpeed"></label>
    <input asp-for="@Model.TopSpeed" />
    <br />
    <button type="submit">Save</button>
</form>

Lab02/WebApplication1/Views/Car/Info.cshtml
@model CarViewModel
@{
    if (ViewBag.Message != null)
    {
        <div>
            @ViewBag.Message
        </div>
    }
}
<hr />
<label asp-for="@Model.Brand"></label> : @Model.Brand  <br />
<label asp-for="@Model.Model"></label> : @Model.Model <br />
<label asp-for="@Model.TopSpeed"></label> : @Model.TopSpeed <br />

Lab02/WebApplication1/Views/Car/List.cshtml
@model List<CarViewModel>
@foreach (var carViewModel in Model)
{
    @Html.Partial("_Car", carViewModel);
}

Lab02/WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Lab02/WebApplication1/Views/Shared/_Car.cshtml
@model CarViewModel
<label asp-for="@Model.Brand"></label> : @Model.Brand
<br />
<label asp-for="@Model.Model"></label> : @Model.Model
<br />
<label asp-for="@Model.TopSpeed"></label> : @Model.TopSpeed
<br />
<hr />

Lab02/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registration" asp-action="Index">Registration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Index">Cars</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>